name: "Test"
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'master'
      - 'ci*' # Allow testing CI fixes without opening a PR

jobs:
  tests:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            # Latest and greatest release of Nix
            install_url: https://nixos.org/nix/install
          - os: ubuntu-latest
            # The 21.11 branch ships with Nix 2.3 but flakes support landed in 2.4
            install_url: https://releases.nixos.org/nix/nix-2.4/install
            nixpkgs-override: "--override-input nixpkgs github:NixOS/nixpkgs/release-21.11"

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        install_url: ${{ matrix.install_url }}
    - uses: cachix/cachix-action@v10
      with:
        name: crane
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: flake checks
      run: nix flake check --print-build-logs ${{ matrix.nixpkgs-override }}
    - name: extra tests
      run: nix develop ${{ matrix.nixpkgs-override }} --command ./extra-tests/test.sh
    - name: validate examples
      run: |
        for f in $(find examples -maxdepth 1 -mindepth 1 -type d); do
          pushd "${f}"
          echo "validating ${f}"
          nix flake check --print-build-logs --override-input crane ../.. ${{ matrix.nixpkgs-override }}
          # Explicitly run .#default so it continues to work with nix versions < 2.8
          nix run .#default --override-input crane ../.. ${{ matrix.nixpkgs-override }}
          popd
        done
