name: Update flake dependencies

on:
  workflow_dispatch: # for allowing manual triggers of the workflow
  schedule:
    - cron: '37 16 3 * *'

permissions:
  contents: read

jobs:
  update-and-push-deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
    - uses: cachix/cachix-action@v11
      with:
        name: crane
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Update flake.lock
      id: flakeupdate
      uses: DeterminateSystems/update-flake-lock@v14
      with:
        token: ${{ secrets.PAT_FLAKE_UPDATE }}
        branch: "automation/flake-update"
        pr-title: "Update flake.lock"
        pr-labels: |
          automated
          dependencies
          flake update

    - uses: peter-evans/enable-pull-request-automerge@v2
      with:
        token: ${{ secrets.PAT_FLAKE_UPDATE }}
        pull-request-number: ${{ steps.flakeupdate.outputs.pull-request-number }}
        merge-method: "squash"
